version: "3.8"

services:
  dynamodb-local:
    restart: always
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - ".verdaccio/storage:/verdaccio/storage"
      - ".verdaccio/config.yml:/verdaccio/conf/config.yml"
      - ".verdaccio/plugins:/verdaccio/plugins"

networks:
  node-network:
    driver: bridge
