Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs16.x
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment

Description: Clean Arch Todos API

# Metadata:
#   template metadata

Parameters:

  Version:
    Type: String
    Default: v1

  Project:
    Type: String
    Default: CleanArchTodos

  Environment:
    Type: String
    Default: dev


# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

Resources:
  
  TodosAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-gw
      StageName: !Ref Version
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./swagger.yml
      Tags:
        Project: !Ref Project
        Environment: !Ref Environment


  TodoLibrary:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs16.x
      ContentUri: ../
      Description: Todo Package Library
      LayerName: todo-pkg-lib
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs16.x


  CreateList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-create-list
      CodeUri: ../dist/create-list/
      Handler: handler.handler
      Layers:
        - !Ref TodoLibrary
      Events:
        PostList:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TodosAPI
            Path: /lists
            Method: POST

  CreateTodo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-create-todo
      CodeUri: ../dist/create-todo/
      Handler: handler.handler
      Layers:
        - !Ref TodoLibrary
      Events:
        PostTodo:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TodosAPI
            Path: /lists/{listId}/todos
            Method: POST

  CreateTodoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateTodo}
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  DeleteTodo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-delete-todo
      CodeUri: ../dist/delete-todo/
      Handler: handler.handler
      Layers:
        - !Ref TodoLibrary
      Events:
        DeleteTodo:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TodosAPI
            Path: /lists/{listId}/todos/{todoId}
            Method: DELETE

  DeleteTodoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeleteTodo}
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  ListTodos:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-list-todos
      CodeUri: ../dist/list-todos/
      Handler: handler.handler
      Layers:
        - !Ref TodoLibrary
      Events:
        GetTodo:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TodosAPI
            Path: /lists/{listId}/todos
            Method: GET

  ListTodosLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ListTodos}
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

# Outputs:
#   set of outputs
