version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "todos-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-67u53hb19nc2"
s3_prefix = "todos-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Version=\"v1\" Project=\"CleanArchTodos\" Environment=\"dev\""
image_repositories = []
