Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 512
    Runtime: nodejs16.x
    Layers:
      - !Ref TodoLibrary
    Environment:
      Variables:
        DYNAMO_TABLE_NAME: !Ref EventStore
        SNS_TOPIC_ARN: !Ref Mediator
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment

Description: Clean Arch Todos API

# Metadata:
#   template metadata

Parameters:
  Version:
    Type: String
    Default: v1

  Project:
    Type: String
    Default: CleanArchTodos

  Environment:
    Type: String
    Default: dev

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

Resources:
  TodosAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-gw
      StageName: !Ref Version
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./swagger.yml
      Tags:
        Project: !Ref Project
        Environment: !Ref Environment

  Mediator:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-mediator
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  EventStore:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-event-store
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: stream
          AttributeType: "S"
        - AttributeName: timestamp
          AttributeType: "N"
      KeySchema:
        - AttributeName: stream
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  TodoLibrary:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs16.x
      ContentUri: ../
      Description: Todo Package Library
      LayerName: todo-pkg-lib
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs16.x

  CreateList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-create-list
      Timeout: 30
      CodeUri: ../dist/create-list/
      Handler: handler.handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        PostList:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TodosAPI
            Path: /lists
            Method: POST

  CreateListLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateList}
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  CreateTodo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-create-todo
      Timeout: 30
      CodeUri: ../dist/create-todo/
      Handler: handler.handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        PostTodo:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TodosAPI
            Path: /lists/{listId}/todos
            Method: POST

  CreateTodoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateTodo}
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  DeleteTodo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-delete-todo
      Timeout: 30
      CodeUri: ../dist/delete-todo/
      Handler: handler.handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        DeleteTodo:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TodosAPI
            Path: /lists/{listId}/todos/{todoId}
            Method: DELETE

  DeleteTodoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeleteTodo}
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  ListTodos:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-list-todos
      Timeout: 30
      CodeUri: ../dist/list-todos/
      Handler: handler.handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GetTodo:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref TodosAPI
            Path: /lists/{listId}/todos
            Method: GET

  ListTodosLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ListTodos}
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  StoreEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: !Sub ${AWS::StackName}-store-queue
      VisibilityTimeout: 900
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  StoreEventSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref Mediator
      Endpoint: !GetAtt StoreEventQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true

  StoreEvent:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      FunctionName: !Sub ${AWS::StackName}-store-event
      CodeUri: ../dist/store-event/
      Handler: handler.handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        OnSQSEvent:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: true
            Queue: !GetAtt StoreEventQueue.Arn

  StoreEventLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${StoreEvent}
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
# Outputs:
#   set of outputs
