name: publish

on:
  push:
    tags:
      - todos-cli-v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@alexx666"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run publish -- --@alexx666:registry="https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
