name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: master
