name: tests

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**/README.md"
      - "docs/**"

env:
  NX_BASE: origin/master
  NX_HEAD: HEAD

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint:affected

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test:affected
